[package]
name = "obsidian-to-html"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
regex = "1.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
